<img src='https://drive.google.com/uc?export=view&id=1SAQBpoqGzB5CT9lwxj1T0h0qVU5p6sdW' width=200 style="float:center">

# NumPy
---
Numpy é uma biblioteca para computação científica em Python

* torna mais fácil a criação e operação de arrays multidimensionais.

* Python é mais lento que linguagens como C e Fortran.

* Numpy fornece uma interface com códigos compilados (e otimizados) em C e Fortran, permitindo que as operações relativas a arrays sejam computadas de maneira mais rápida.

**Índice:**
1. [Criando objetos](#I.-Criando-objetos)
2. [Manipulações](#II.-Manipulações)
3. [Operações](#III.-Operações)
4. [Álgebra linear](#IV.-Álgebra-linear)

**Vídeos:**
* Playlist: https://youtube.com/playlist?list=PLdI5ScTnQlX85-ZUAk6i3Qr4yK-73XaA3

**Fontes:**
* [Aula de Python da UFRJ](https://dcc.ufrj.br/~pythonufrj/aulas-python2_37/aula7_teorica.pdf)
* [Números aleatórios](https://www.howtogeek.com/183051/htg-explains-how-computers-generate-random-numbers/)
* [Manual de referência scypy/numpy](https://docs.scipy.org/doc/numpy/reference/)

In [ ]:
%%HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLdI5ScTnQlX85-ZUAk6i3Qr4yK-73XaA3" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Importando a biblioteca Numpy e a biblioteca MatplotLib

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

## I. Criando objetos
---
**Índice:**
1. [Arrays](#1-Arrays)
2. [Arrays pré-moldados](#2-Arrays-pré-moldados)
3. [Matrizes pré-moldadas](#3-Matrizes-pré-moldadas)
4. [Números aleatórios](#4-Números-aleatórios)

**Vídeo:** https://youtu.be/1WNPhouZjcA

### 1 Criando arrays
Arrays do numpy são multidimensionais
```python
array(object, dtype=None, copy=True, order='K', ndmin=0)
```

In [ ]:
x = np.array([1, 2, 3])
x

In [ ]:
x.dtype

In [ ]:
y = np.array([[1., 0., 2.], [0., 1., 2.]])
y

In [ ]:
y.dtype

In [ ]:
print(type(y))

Cada dimensão em Numpy é chamada de eixo (axes):
* `x`: `[1,2,3]` tem dimensão (rank) 1 e seu eixo tem comprimento 3. Pode ser visto como um vetor.
* `y`: `[[1.,0.,2.],[0.,1.,2.]]` tem dimensão (rank) 2. O primeiro eixo tem comprimento 2,e o segundo tem comprimento 3.Pode ser visto como uma matriz 2x3

Criando um array com um tipo específico de dados

In [ ]:
np.array(x, dtype='float32')

Criando um array com o número de dimensões especificadas

In [ ]:
np.array(x, ndmin=3), np.array(x, ndmin=3).shape

#### Acessando elementos

In [ ]:
x[1]

Acesso a primeira dimensão

In [ ]:
y[0]

In [ ]:
y[0][1]

In [ ]:
y[0, 1]

Utilizando o método `numpy.arange`
```python
np.arange([start,] stop[, step,], dtype=None)
```

In [ ]:
np.arange(1,11,2, dtype='float64')

Utilizando o método `numpy.linspace`
```python
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
```

In [ ]:
np.linspace(0, 9, num=9, retstep=True)

In [ ]:
x = np.linspace((0,1), (9,9), axis=0, num=10)
x

In [ ]:
x.shape

In [ ]:
y = np.linspace((0,1), (9,9), axis=1, num=10)
y

In [ ]:
y.shape

### 2 Arrays  pré-moldados
Arrays preenchidos com 0:
```python
np.zeros(shape, dtype=None, order='C')
np.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
```
Arrays preenchidos com 1:
```python
np.ones(shape, dtype=None, order='C')
np.ones_like(a, dtype=None, order='K', subok=True, shape=None)
```
Arrays preenchidos com números quaisquer: 
```python
np.empty(shape, dtype=None, order='C')
np.empty_like(a, dtype=None, order='K', subok=True, shape=None)
```

Arrays preenchidos com o número escolhido:
```python
np.full(shape, fill_value, dtype=None, order='C')
np.full_like(a, fill_value, dtype=None, order='K', subok=True, shape=None)
```

In [ ]:
np.ones((2,3,4))

In [ ]:
np.ones_like(y)

In [ ]:
np.empty((2,1))

In [ ]:
np.full((1,2), 3)

### 3 Matrizes pré-moldadas

#### Diagonal unitária
Matriz com diagonal igual a 1 e 0 fora da diagonal:
```python
np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
```

In [ ]:
np.eye(3, M=2, k=-1)

#### Identidade
Matriz quadrada identidade:
```python
np.identity(n, dtype=None)
```


In [ ]:
np.identity(3)

#### Diagonal
Matriz diagonal com valores especificados:
```python
np.diag(v, k=0)
```
*Também é possível extrair a diagonal de uma matriz com o método `np.diag`*

In [ ]:
np.diag([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
np.diag([1, 5, 9])

#### Exercício 1
Faça uma função que dado um intervalo fechado $[a, b]$ e um número de pontos $n$, retorna o array `x`, formado pelos $n$ pontos obtidos a partir do intervalo $[a, b]$ e `y` é o array onde $y_i = x_i^2 - 9$.

**Exemplo**
```python
>> x, y = f([−10, 10], 10)
>>
>> print(x)
array([−10., −7.77777778, −5.55555556, −3.33333333, −1.11111111, 1.11111111, 3.33333333, 5.55555556, 7.77777778, 10.]
>>
>> print(y)
array([91., 51.49382716, 21.86419753, 2.11111111, −7.7654321, −7.7654321, 2.11111111, 21.86419753, 51.49382716, 91.])
```

#### Exercício 2
Crie uma função gera_matriz que recebe como parâmetros de entrada (a, b, n, m). Que retorne um array Numpy de formato $m \times m$, onde os elementos são os $n$ números igualmente espaçados obtidos ao se dividir o intervalo $[a, b]$. Caso não seja possível construir tal array, a função deve retornar a mensagem `"Não é possível construir"`.

**Exemplo:**
```python
>> gera_matriz(0 ,10 ,16 ,4)
array([[0., 0.66666667, 1.33333333, 2.]
      [2.66666667, 3.33333333, 4., 4.66666667],
      [5.33333333, 6., 6.66666667, 7.33333333],
      [8., 8.66666667, 9.33333333, 10.]])
>>
>> gera_matriz(0, 10, 10, 4)
"Não é possível construir"
```

### 4 Números aleatórios
Existem dois tipos de números aleatórios, os aleatórios verdadeiros (medida de uma grandeza física externa ao computador) e os pseudo aleatórios.

**Números aleatórios verdadeiros:**
* Decaimento da radiação de um átomo;
    * Pela teoria quântica, não há forma de saber ao certo quando o decaimento da radiação ocorrerá.
* Movimento do mouse;
* Barulho ambiente;
* Instante de tempo;

**Números pseudo-aleatórios:**
* Algorítmo função de uma semente (*seed*);

**Fontes:**
* [How to Geek](https://www.howtogeek.com/183051/htg-explains-how-computers-generate-random-numbers/)

**Video:** https://youtu.be/yaKpXKN3P7o

In [ ]:
np.random.seed(42)

Arrays com números aleatório entre 0 e 1 com distribuição uniforme:
```python
rand(d0, d1, ..., dn)
```

In [ ]:
np.random.rand(3,3)

In [ ]:
x = np.random.rand(10000)
plt.hist(x);
plt.title('Dist. Uniforme com média %.2f e variância %.2f'%(x.mean(), x.var()));

Número inteiro aleatório com distribuição uniforme:
```python
np.random.randint(low, high=None, size=None, dtype=int)
```

In [ ]:
np.random.randint(0, 10, size=(3,3))

In [ ]:
x = np.random.randint(0, 10, size=10000)
plt.hist(x);
plt.title('Dist. Uniforme com média %.2f e variância %.2f'%(x.mean(), x.var()));

Array de números aleatórios entre 0 e 1 com distribuição normal $N(0,1)$:
```python
np.random.randn(d0, d1, ..., dn)
```

In [ ]:
np.random.randn(3,3)

In [ ]:
x = np.random.randn(10000)
plt.hist(x);
plt.title('Dist. Normal com média %.2f e variância %.2f'%(x.mean(), x.var()));

Amostragem aleatória:
```python
np.random.choice(a, size=None, replace=True, p=None)
```

In [ ]:
np.random.choice(range(10), size=10, replace=True)

Ordenação aleatória:
```python
np.random.shuffle(x)
```

In [ ]:
x = list('random')
np.random.shuffle(x)
x

## II. Manipulações
---
**Índice:**
1. [Formato](#1-Formato)
2. [Indexação e fatiamento](#2-Indexação-e-fatiamento)
3. [Indexação por máscara](#3-Indexação-por-máscara)

**Video:** https://youtu.be/GgW1gQOh2Oo

### 1 Formato
```python
a.flat                      # Iterador 1-D sobre o array
a.flatten(order='C')        # Retorna a cópia do array em 1-D
a.ravel(a[, order])         # Retorna o array em 1-D
a.reshape(shape, order='C') # Retorna um array remodelado no formato que é passado
```

In [ ]:
a = np.arange(20).reshape(10, 2)
print('a = np.arange(20).reshape(10, 2)')
print(a)
print()
print('[i for i in a.flat] =')
print([i for i in a.flat])
print()
print('a.flatten() =')
print(a.flatten())
print()
print('a.ravel() =')
print(a.ravel())

### 2 Indexação e fatiamento
Funciona de forma similar às operações com listas

In [ ]:
x = list('palavra')
x[1:3]

In [ ]:
y = np.array(list('palavra'))
y[1:3]

As diferenças começam quando fatiamos a `list` e o array para criar uma visualização, na `list` é realizada uma cópia do pedaço da `list` original:

In [ ]:
x = list('palavra')

x0 = x[0:2]
x0[0] = 5
x, x0

Ao realizaro o mesmo procedimento em um array, apontamos para o mesmo trecho de memória:

In [ ]:
y = np.array(list('palavra'))

y0 = y[0:2]
y0[0] = 5
y, y0

**Atenção**

Para não afetar o array original, podemos utilizar o método `np.ndarray.copy()`.

In [ ]:
y = np.array(list('palavra'))

y0 = y[0:2].copy()
y0[0] = 5
y

#### Exercício 3
Faça duas funções, linha e coluna, cada uma recebendo como parâmetro de entrada um array `M` e um número inteiro $i$. O formato $(n, m)$ do array `M` não é passado como parâmetro de entrada. As funções devem retornar, respectivamente, a linha e a coluna $i$ de `M`. Se `M` não possui linha (coluna) $i$, a mensagem `"Não existe esta linha (coluna)"` deve ser retornada.
Caso `M` não tenha o formato $(n, m)$, a mensagem `"Isto nao e uma matriz."` deve ser retornada.

**Exemplo**
```python
>> z
array([[0.,1.11111111,2.22222222,3.33333333,4.44444444],
       [5.55555556,6.66666667,7.77777778,8.88888889,10.]])
>>
>> w
array([[[0., 1.03846154, 2.07692308],
        [3.11538462, 4.15384615, 5.19230769],
        [6.23076923, 7.26923077, 8.30769231]],
       [[9.34615385, 10.38461538, 11.42307692],
        [12.46153846, 13.5, 14.53846154],
        [15.57692308, 16.61538462, 17.65384615]],
       [[18.69230769, 19.73076923, 20.76923077],
        [21.80769231, 22.84615385, 23.88461538],
        [24.92307692, 25.96153846, 27.]]])
>>
>> coluna(z, 4)
array([4.44444444, 10.])
>>
>> linha(z, 5)
"Não existe esta linha"
>>
>> linha(w, 3)
"Isto não é uma matriz"
```

### 3 Indexação por Máscara
É possível indexar e fatiar os `numpy.ndarrays` utilizando booleanos.

In [ ]:
t = np.linspace(0, 10, 1000)
x = t**2
plt.plot(t, x)
plt.show()

In [ ]:
mask1 = (t >= 2.5) & (t < 5.0)
mask2 = t >= 5.0

x[mask1] = t[mask1][0]**2
x[mask2] = t[mask2]**2 - (t[mask2][0]**2 - t[mask1][0]**2)

plt.plot(t, x, t[mask1], x[mask1], t[mask2], x[mask2])
plt.show()

## III. Operações
---
**Índice:**
1. [Básicas](#1-Básicas)
2. [Vetoriais e matriciais](#2-Vetoriais-e-matriciais)
3. [Broadcasting](#3-Broadcasting)
4. [Métodos de arrays](#4-Métodos-de-arrays)
5. [Estatística](#5-Estatística)
6. [Métodos universais](#6-Métodos-universais)
7. [Vetorizando funções](#7-Vetorizando-funções)

**Vídeo:** https://youtu.be/C3OCpKJMJZ0

### 1 Básicas
Operações de array com uma constante
* Aritiméticas: `+, -, *, /, //, %`
* Comparação: `==, !=, >, >=, <, <=`
* Booleanas: `[&](and), [|](or), [^](xor), [~](not)`


In [ ]:
x = np.arange(6)

In [ ]:
print('x:            ', x)
print('Operações com o número 2.')
print('Soma:         ', x+2)
print('Subtração:    ', x-2)
print('Multiplicação:', x*2)
print('Divisão:      ', x/2)
print('Exponenciação:', x**2)
print('Quociente:    ', x//2)
print('Resto:        ', x%2)

In [ ]:
print('x:             ', x)
print('Comparação com o número 3.')
print('Igual:         ', x==3)
print('Diferente:     ', x!=3)
print('Maior:         ', x>3)
print('Maior ou igual:', x>=3)
print('Menor:         ', x<3)
print('Menor ou igual:', x<=3)

In [ ]:
x = np.array([i%2 == 0 for i in range(4)])

In [ ]:
print('x:  ', x)
print('Comparação com True')
print('And:', x & True)
print('Or: ', x | True)
print('Xor:', x ^ True)
print('Not:', ~x)

### 2 Operações vetoriais e matriciais

In [ ]:
x = np.random.randint(0, 10, size=(3,2))
y = np.random.randint(0, 10, size=(3,2))
z = np.random.randint(0, 10, size=(2,3))
print(x, y, z, sep='\n\n')

Operações termo a termo.

In [ ]:
x + y

In [ ]:
x - y

In [ ]:
x * y

In [ ]:
x / y

Multiplicação matricial

Para que a multiplicação ocorra, é necessário que o número de colunas da matriz à esquerda seja igual ao número de linhas da matriz à direita:

$$
\left[
    \begin{matrix}
    a & b & c \\
    e & f & g
    \end{matrix}
\right] \cdot
\left[
    \begin{matrix}
    A & B \\
    C & D \\
    E & F
    \end{matrix}
\right] = 
\left[
    \begin{matrix}
    Aa + Cb + Ec & Ba + Db + Fc \\
    Ae + Cf + Eg & Be + Df + Fg
    \end{matrix}
\right]
$$

In [ ]:
print(x, z, sep='\n\n')
print('\nx @ z =')
x @ z

In [ ]:
x.dot(z)

### 3 Broadcasting

O NumPy possui a capacidade de aumentar o tamanho de um array automaticamente para realizar uma operação, isto se chama broadcasting:

$$
\left[
    \begin{matrix}
    a & b & c \\
    e & f & g
    \end{matrix}
\right] +
\left[
    \begin{matrix}
    A & B & C
    \end{matrix}
\right] \Rightarrow
\left[
    \begin{matrix}
    a & b & c \\
    e & f & g
    \end{matrix}
\right] +
\left[
    \begin{matrix}
    A & B & C \\
    A & B & C
    \end{matrix}
\right]
$$

In [ ]:
x = np.ones((2, 3))*3
y = np.ones((1, 3))*2

In [ ]:
print('x:\n', x)
print('y:\n', y)
print()
print('x + y:\n', x + y)
print('x * y:\n', x * y)

### 4 Métodos de arrays

```python
np.sum(a, axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)
np.prod(a, axis=None, dtype=None, , out=None, keepdims=False, initial=0, where=True)
np.cumsum(a, axis=None, dtype=None, out=None)
np.cumprod(a, axis=None, dtype=None, out=None)
```

In [ ]:
print('Somatório:')
print(x.sum())
print('Produtório:')
print(x.prod(axis=1))
print('Soma acumulada:')
print(x.cumsum())
print('Produto acumulado:')
print(x.cumprod(axis=0))

### 5 Estatística

```python
# Mínimo
np.min(a, axis=None, out=None, keepdims=False, initial=<no value>, where=True)

# Máximo
np.max(a, axis=None, out=None, keepdims=False, initial=<no value>, where=True)

# Percentil
np.percentilenp.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)

# Quartil
np.quantile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)

# Média
np.mean(a, axis=None, dtype=None, out=None, keepdims=numpy._globals._NoValueType instance)

# Mediana
np.median(a, axis=None, out=None, overwrite_input=False, keepdims=False)

# Desvio Padrão
np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=numpy._globals._NoValueType instance)

# Variância
np.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=numpy._globals._NoValueType instance)
```

In [ ]:
x = np.random.randint(0, 10, size=(10))

In [ ]:
print('x:             ', sorted(x))
print('Máximo:        ', x.max())
for i in range(90,0,-10):
    if i == 70:
        print('Percentil 75 % = 3º Quartil:', np.quantile(x, .75))
    if i == 20:
        print('Percentil 25 % = 1º Quartil:', np.quantile(x, .25))
    if i == 50:
        print('Percentil 50 % = 2º Quartil = Mediana:', np.percentile(x, i))
    else:
        print('Percentil %d %%:'%i, np.percentile(x, i))
print('Mínimo:        ', x.min())

In [ ]:
print('Desvio Padrão:', x.std())
print('Variância:    ', x.var())

In [ ]:
plt.boxplot(x);
plt.grid(axis='y')

### 6 Métodos universais
Métodos do NumPy para cálculo elemento a elemento de operação
```python
np.exp()
np.sqrt()
np.power()
np.log()
np.log10()
np.log2()

np.sin()
np.cos()
np.tan()
np.arc...()

np.sinh()
np.cosh()
np.tanh()
np.arc...()
```

In [ ]:
x = np.sort(np.random.rand(1000))
y = np.array([np.exp(x), np.log(x), np.cos(x*2*np.pi)])
print('x:', x.shape)
print('y:', y.shape)

É necessário transpor o y pois o Matplotlib entende que as ordenadas possuem  1000 pontos, logo as abscissas devem possuir 1000 linhas!

Assim, cada uma das três colunas é identificada como um conjunto de dados diferentes.


In [ ]:
plt.plot(x, y.T)

# ao utilizar o $, o matplotlib invoca o LaTeX para imprimir uma equação
plt.legend(['$e^x$', '$\log(x)$', '$\cos(2\pi x)$']);

### 7 Vetorizando funções

In [ ]:
x = np.random.randn(10)
x

In [ ]:
def f(x):
    if x > 0:
        return 1
    else:
        return 0

f(x)

Funções definidas pelo usuário normalmente não são vetorizadas, ou seja, aplicáveis termo a termo em vetores.

É possível vetorizar funções com o numpy.

In [ ]:
f_vect = np.vectorize(f)
f_vect(x)

#### Exercício 4
Considere a expressão polinomial:
$$p(x) = a_0 + a_1x + a_2x^2 +\ ...\ + a_Nx^N = \sum^N_{n=0}{a_nx^n}$$

Escreva uma função que utilize arrays e operações em arrays NumPy para calcular tal polinômio, sem usar `for` ou `while`.

Dica: use `np.cumprod()` ou `np.vectorize()`.

#### Exercício 5
Seja $q$ um array NumPy de comprimento $n$ com $\sum{q} = 1$.

Suponha que $q$ representa uma [função densidade de probabilidade](https://en.wikipedia.org/wiki/Probability_mass_function). Queremos gerar uma variável aleatória discreta $X$ tal que $P\{X=i\} = q_i$. Em outras palavras, $X$ toma valores em $range(len(q))$ e $x = i$ com probabilidade $q[i]$.

O algoritmo (transformação inversa) padrão é como segue:
* Divida o intervalo $[0,1]$ em $n$ subintervalos $I_0, I_1,\ ..., I_{n1}$ tal que o comprimento de $I_i$ é $q_i$
* Sorteie uma variável aleatória uniforme $U \in [0,1]$ e retorne $i$ tal que $U \in I_i$

A probabilidade de sortear $i$ é o comprimento de $I_i$, que é igual a $q_i$. Podemos implementar o algoritmoda seguinte forma:

```python
from random import uniform
def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]
```

Se você não entendeu como isso funciona, tente pensar usando um exemplo simple, tal como $q = [0.25,0.75]$. Ajuda se você esboçar os intervalos no papel. Seu exercício é aumentar a velocidade usando Numpy, evitando laços explícitos.

Dica: use `np.searchsorted` e `np.cumsum`.
Exemplificando de maneira gráfica.

Existem 4 cores de bolas em um saco com 100 bolas.

|Cor|Quantidade|Probabilidade|Probabilidade Acumulada|
|-|-:|-:|-:|
|Azul|25|0.25|0.25|
|Verde|25|0.25|0.50|
|Vermelha|35|0.35|0.85|
|Preta|15|0.15|1.00|

Realizamos uma amostragem aleatória das bolas:

In [ ]:
from random import uniform
def sample(q):
    if np.sum(q) != 1:
        raise ValueError('Não é função densidade de probabilidade.')
    a = 0.0
    U = uniform(0, 1)

    # Gerando o gráfico explicativo
    cs = list('bgrk')
    plt.figure(figsize=(15,1))
    plt.scatter(np.array(q).cumsum(), np.zeros_like(q), c=cs)
    plt.xlim((0,1.1))
    plt.box(False)
    plt.grid(True)
    plt.yticks([])
    cores = ['Azul', 'Verde', 'Vermelha', 'Preta']
    intervalos = np.array([0] + q).cumsum()
    for i, cor in enumerate(cores):
        plt.annotate(cor, (np.array(q).cumsum()[i], 0.01), c=cs[i])
        plt.annotate('Intervalo %d'%i,
                     ((intervalos[i]+intervalos[i+1])/2, 0.04),
                     c=cs[i],
                     ha='center')
    for i in range(len(intervalos)-1):
        plt.hlines(0, intervalos[i], intervalos[i+1], cs[i])
    plt.plot(U, 0, marker='x', c='m')
    plt.annotate('Var. Aleat.', (U, -0.025), c='m')
    
    print('Variável aleatória uniforme U =', U)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            print('Bola sorteada:', cores[i])
            return i
        a = a + q[i]

d = [.25, .25, .35, .15]
%time i = sample(d)
print('Amostrado o intervalo',i)

## IV. Álgebra linear
---

**Vídeo:** https://youtu.be/XxwYMjYU5PY

Métodos:
```python
np.linalg.norm(x, ord=None, axis=None, keepdims=False) # Norma
np.linalg.inv(A)                                       # Inversão de A
np.linalg.solve(A, b)                                  # Resolve o sistema linear de "Ax = b"
np.linalg.det(A)                                       # Determinante de A
np.linalg.lstsq(a, b, rcond='warn')                    # Mínimos quadrados
np.linalg.matrix_power(A, n)                           # Eleva "A" a potência "n"
np.linalg;matrix_rank(M, tol=None, hermitian=False)    # Retorna o posto da matriz
np.linalg.eig(A)                                       # Autovalores e autovetores de A
np.linalg.qr(a, mode='reduced')                        # Decomposição QR
np.linalg.cholesky(A)                                  # Decomposição Cholesky
```

#### Exercício 6
Simulando um sensor com erros de medida.
Sabendo-se que um sensor está medindo a temperatura ($T$) de um tanque, conforme dados abaixo, calcule a taxa de variação da temperatura. O tempo é representado por $t$, expresso em minutos.

O sensor possui um erro de 3%.

Dica: Utilize o método [`lstsq`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.lstsq.html).

In [ ]:
Temp = lambda t: (30 + t/10)+(np.random.randn(len(t))*(30 + t/10)*.03)

In [ ]:
t = np.linspace(0, 100, 1000)
T = Temp(t)

plt.scatter(t, T, marker='.')
plt.xlabel('$t$ [min]')
plt.ylabel('$T$ [ºC]')
plt.title('TT-1210003A')
plt.grid()
plt.show()